# This file is automatically synced from:
# https://github.com/autowarefoundation/sync-file-templates
# To make changes, update the source repository and follow the guidelines in its README.

# Deprecated: Consider removing this workflow if your `.pre-commit-config.yaml` is synced.

name: pre-commit-autoupdate

on:
  schedule:
    - cron: 0 0 1 1,4,7,10 * # quarterly
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit-autoupdate:
    runs-on: ubuntu-22.04
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Run pre-commit-autoupdate
        uses: autowarefoundation/autoware-github-actions/pre-commit-autoupdate@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pre-commit-config: .pre-commit-config.yaml
          pr-labels: |
            tag:bot
            tag:pre-commit-autoupdate
          pr-branch: pre-commit-autoupdate
          pr-title: "ci(pre-commit): autoupdate"
          pr-commit-message: "ci(pre-commit): autoupdate"
          auto-merge-method: squash
